name: Deploy Application

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build  # Change this if your build command is different

      - name: Deploy
        run: |
          # Add your deployment commands here
          # For example, if you are deploying to a server via SSH:
          # ssh user@your-server "cd /path/to/your/app && git pull && npm install && npm run start"
